// Mock vehicle data with diverse selection
export const MOCK_VEHICLES = [
  {
    id: "1",
    name: "Toyota Fortuner 2023",
    image: "https://images.unsplash.com/photo-1742697167580-af91e3ead35e?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 8500,
    seats: 7,
    transmission: "Automatic" as const,
    fuelType: "Diesel",
    year: 2023,
    rating: 4.8,
    location: "Nairobi",
    category: "SUV",
    features: ["4WD", "Leather Seats", "Sunroof", "GPS Navigation"],
    description: "Perfect for family trips and off-road adventures. Spacious and comfortable.",
  },
  {
    id: "2",
    name: "Nissan X-Trail 2022",
    image: "https://images.unsplash.com/photo-1551817280-6d59c77ce1b8?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 6500,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Petrol",
    year: 2022,
    rating: 4.6,
    location: "Mombasa",
    category: "SUV",
    features: ["Bluetooth", "Backup Camera", "Climate Control"],
    description: "Reliable crossover SUV ideal for city and highway driving.",
  },
  {
    id: "3",
    name: "Subaru Forester 2021",
    image: "https://images.unsplash.com/photo-1687048988997-ec57f83ea3bd?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 5500,
    seats: 5,
    transmission: "Manual" as const,
    fuelType: "Petrol",
    year: 2021,
    rating: 4.7,
    location: "Nairobi",
    category: "SUV",
    features: ["AWD", "Roof Rails", "Heated Seats"],
    description: "Adventure-ready with excellent safety ratings and AWD capability.",
  },
  {
    id: "4",
    name: "Toyota Prado 2024",
    image: "https://images.unsplash.com/photo-1533473359331-35acde7260c9?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 9500,
    seats: 7,
    transmission: "Automatic" as const,
    fuelType: "Diesel",
    year: 2024,
    rating: 4.9,
    location: "Nairobi",
    category: "SUV",
    features: ["Premium Sound", "Leather Interior", "Adaptive Cruise", "Lane Assist"],
    description: "Luxury SUV with premium features and exceptional comfort.",
  },
  {
    id: "5",
    name: "Honda CR-V 2023",
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 7000,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Hybrid",
    year: 2023,
    rating: 4.7,
    location: "Nairobi",
    category: "SUV",
    features: ["Hybrid Engine", "Apple CarPlay", "Panoramic Sunroof"],
    description: "Eco-friendly hybrid with excellent fuel economy and modern tech.",
  },
  {
    id: "6",
    name: "Mazda CX-5 2022",
    image: "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 6000,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Petrol",
    year: 2022,
    rating: 4.5,
    location: "Kisumu",
    category: "SUV",
    features: ["Bose Sound System", "Head-Up Display", "Smart Brake"],
    description: "Stylish and sporty crossover with premium interior quality.",
  },
  {
    id: "7",
    name: "Toyota Corolla 2023",
    image: "https://images.unsplash.com/photo-1623869675781-80aa31012a5a?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 4500,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Petrol",
    year: 2023,
    rating: 4.6,
    location: "Nairobi",
    category: "Sedan",
    features: ["Fuel Efficient", "Bluetooth", "Backup Camera"],
    description: "Reliable and economical sedan perfect for daily commutes.",
  },
  {
    id: "8",
    name: "Mercedes-Benz C-Class 2023",
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 12000,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Petrol",
    year: 2023,
    rating: 4.9,
    location: "Nairobi",
    category: "Luxury",
    features: ["Premium Leather", "Ambient Lighting", "Burmester Sound", "Massage Seats"],
    description: "Ultimate luxury sedan with cutting-edge technology and comfort.",
  },
  {
    id: "9",
    name: "BMW X5 2024",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 15000,
    seats: 7,
    transmission: "Automatic" as const,
    fuelType: "Diesel",
    year: 2024,
    rating: 4.9,
    location: "Nairobi",
    category: "Luxury",
    features: ["Panoramic Roof", "Harman Kardon", "Gesture Control", "Night Vision"],
    description: "Premium luxury SUV with advanced driver assistance systems.",
  },
  {
    id: "10",
    name: "Volkswagen Polo 2022",
    image: "https://images.unsplash.com/photo-1622353219448-46a009f0d44f?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 3500,
    seats: 5,
    transmission: "Manual" as const,
    fuelType: "Petrol",
    year: 2022,
    rating: 4.4,
    location: "Mombasa",
    category: "Compact",
    features: ["Compact Size", "Easy Parking", "Fuel Efficient"],
    description: "Perfect city car with great fuel economy and easy maneuverability.",
  },
  {
    id: "11",
    name: "Suzuki Swift 2023",
    image: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 3800,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Petrol",
    year: 2023,
    rating: 4.5,
    location: "Nakuru",
    category: "Compact",
    features: ["Touchscreen", "Reverse Camera", "Keyless Entry"],
    description: "Sporty hatchback with modern features and zippy performance.",
  },
  {
    id: "12",
    name: "Land Rover Defender 2024",
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 18000,
    seats: 7,
    transmission: "Automatic" as const,
    fuelType: "Diesel",
    year: 2024,
    rating: 4.8,
    location: "Nairobi",
    category: "Luxury",
    features: ["Terrain Response", "Wade Sensing", "Air Suspension", "Meridian Sound"],
    description: "Iconic off-roader with unmatched capability and luxury.",
  },
  {
    id: "13",
    name: "Mitsubishi Outlander 2022",
    image: "https://images.unsplash.com/photo-1581540222194-0def2dda95b8?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 5800,
    seats: 7,
    transmission: "Automatic" as const,
    fuelType: "Petrol",
    year: 2022,
    rating: 4.4,
    location: "Eldoret",
    category: "SUV",
    features: ["Third Row Seating", "All-Wheel Control", "Apple CarPlay"],
    description: "Spacious family SUV with three rows and AWD capability.",
  },
  {
    id: "14",
    name: "Hyundai Tucson 2023",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 6200,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Petrol",
    year: 2023,
    rating: 4.6,
    location: "Nairobi",
    category: "SUV",
    features: ["Digital Cockpit", "Wireless Charging", "Smart Cruise Control"],
    description: "Modern SUV with futuristic design and advanced safety features.",
  },
  {
    id: "15",
    name: "Audi Q7 2024",
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=800",
    pricePerDay: 16500,
    seats: 7,
    transmission: "Automatic" as const,
    fuelType: "Diesel",
    year: 2024,
    rating: 4.9,
    location: "Nairobi",
    category: "Luxury",
    features: ["Virtual Cockpit", "Matrix LED", "Bang & Olufsen", "Quattro AWD"],
    description: "Sophisticated luxury SUV with cutting-edge technology.",
  },
];

// Categories for filtering
export const VEHICLE_CATEGORIES = [
  { value: "all", label: "All Vehicles" },
  { value: "SUV", label: "SUVs" },
  { value: "Sedan", label: "Sedans" },
  { value: "Luxury", label: "Luxury" },
  { value: "Compact", label: "Compact" },
];

// Locations
export const LOCATIONS = [
  "Nairobi",
  "Mombasa",
  "Kisumu",
  "Nakuru",
  "Eldoret",
  "Thika",
  "Malindi",
];

// Features/Benefits for homepage
export const BENEFITS = [
  {
    icon: "Shield",
    title: "Fully Insured",
    description: "All vehicles come with comprehensive insurance coverage",
  },
  {
    icon: "Clock",
    title: "24/7 Support",
    description: "Round-the-clock customer service and roadside assistance",
  },
  {
    icon: "DollarSign",
    title: "Best Prices",
    description: "Competitive rates with no hidden fees or charges",
  },
  {
    icon: "CheckCircle",
    title: "Quality Assured",
    description: "Regular maintenance and safety checks on all vehicles",
  },
];

// Testimonials
export const TESTIMONIALS = [
  {
    name: "Sarah Mwangi",
    role: "Business Traveler",
    content: "Excellent service! The booking process was smooth and the car was in perfect condition. Highly recommend for anyone visiting Nairobi.",
    rating: 5,
    avatar: "SM",
  },
  {
    name: "John Kamau",
    role: "Tourist",
    content: "Great experience from start to finish. The team was professional and the vehicle exceeded my expectations. Will definitely use again!",
    rating: 5,
    avatar: "JK",
  },
  {
    name: "Amina Hassan",
    role: "Family Vacation",
    content: "Perfect for our family trip to the coast. The SUV was spacious and comfortable. Customer service was outstanding!",
    rating: 5,
    avatar: "AH",
  },
];

// FAQ Data
export const FAQ_DATA = [
  {
    question: "What documents do I need to rent a vehicle?",
    answer: "You'll need a valid driver's license (held for at least 2 years), national ID or passport, and a valid payment method. International visitors need an International Driving Permit along with their home country license.",
  },
  {
    question: "What is the minimum age to rent a car?",
    answer: "The minimum age is 23 years for standard vehicles and 25 years for luxury or high-performance vehicles. Additional young driver fees may apply for drivers under 25.",
  },
  {
    question: "Is insurance included in the rental price?",
    answer: "Yes, all our rentals include basic insurance coverage. Additional coverage options are available for purchase during booking for extra peace of mind.",
  },
  {
    question: "Can I pick up the car in one city and drop it off in another?",
    answer: "Yes, we offer one-way rentals between major cities. Additional fees may apply depending on the distance and locations involved.",
  },
  {
    question: "What is your fuel policy?",
    answer: "We operate on a full-to-full policy. You'll receive the vehicle with a full tank and should return it full. Alternatively, you can pre-purchase a full tank at competitive rates.",
  },
  {
    question: "What happens if I return the car late?",
    answer: "We offer a 1-hour grace period. After that, late returns are charged at an hourly rate. If you're more than 6 hours late, a full additional day will be charged.",
  },
];
